### ISSUE TITLE
Static/serverless services 

### ISSUE THREAD

**Issue by jayvdb** [pozitron57/open-source-comments#2]
The "static" column is a bit strange, and the choice of which are currently 'yes' feels a bit arbitrary.
Unless the commenter has privileges to write to the webserver, no comment system can be 100% static.
Even serverless have a server, but I dont need to worry about the server.

For a JAMstack / static website, I think there are two two main aspects are:

1. Is the software hosted , or hostable 'easily' using free/low-cost *aaS providers.

Any software that is hosted or "yes" for question one is suitable for static/serverless/JAMstack websites, and need to be compared on other factors.  Authentication is one of the first factors to eliminate many options.

Which authentication providers are provided by the hoster.  e.g. GitHub based comment storage solutions will require users create/use a GitHub account, which may not be suitable for many audiences.

2. The next is how much of the comment server does the website provider have to manage.

Discourse is at one end of that spectrum ;-)  Staticman is at the other. Most ppl want something in the middle.  The current table currently doesnt help the reader to find the sweet spot for them, as their is no ordering or filtering on column values.  Maybe a set of filter selectors like "Docker", "Heroku" "AWS" , etc.

**Comment by pozitron57** [comment]
Thank you for the feedback!

By "Static" I mean those comments which are built into the html code, i.e. one can find it in the source code of the page. It is, I think, a quite important point — for example, the comment will be visible even if visitor has javascript disabled. It should be certainly clarified on the page, possibly with a tooltip on mouse over.

>The current table currently doesnt help the reader to find the sweet spot for them

Agree. I am striving for that, but at first I want to collect the information. Once it is more or less done, it will be easier decide how it is better to present it. Meanwhile I try to understand which features of commenting systems are “sweet spots” for users (that's why any feedback is greatly appreciated). Also I think it is good to have a kind of "short description" and "long description". Currently "description" is not very uniform and helpful.

>...as their is no ordering or filtering on column values

Is the ordering not working for you? It should work by clicking on columns' headers. Filtering is possible using "search".

If you propose to add new columns such as "Possible to run on Heroku", you are welcome to submit a PR on this. I have never used any *aaS service and don't know much about it.
